### ISSUE TITLE
Создание графических ассетов

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#10]
Создать графические ассеты:
- [x] преграды на уровне
- [x] платформы на уровне
- [x] двери 
- [x] ключи

**Comment by ilynn-zip** [comment]
2630e85 : добавлены тайлы карты и ассеты

**Comment by ilynn-zip** [comment]
@ZhuravlevE просмотри, если понравились закрой.
старался использовать минималистичный вид, чтобы игроку всё было понятно.
некоторые преграды на уровне можно реализовать через компоненты движка, так будет удобнее.
старался соблюдать стилистику главного персонажа - телевизора
т.е. дверь - это экранные помехи, а ключ - штепсельная вилка.

**Comment by ZhuravlevE** [comment]
Создали графические ассеты
