### ISSUE TITLE
Разработка уровней

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#15]
Создать уровень 1, уровень должен содержать красных НИПов для поэтапного ознакомления игрока с базовыми механиками, на этом уровне игрок должен научиться создавать красных активных НИПов, понять принцип их действия и прыгать по ним:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 2, уровень должен содержать зеленых НИПов для поэтапного ознакомления игрока с базовыми механиками, на этом уровне игрок должен научиться создавать зеленых неподвижных НИПов и прыгать по ним:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 3, уровень должен содержать зеленых и красных НИПов для поэтапного ознакомления игрока с базовыми механиками, на этом уровне игрок должен научиться планировать создание НИПов (НИПы в стеке не всегда идут в удобном для игрока порядке), и использовать красного НИПа для подбора недосягаемого для персонажа ключа, а затем отбирать его у красного НИПа:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 4, уровень должен содержать зеленых и красных НИПов для поэтапного ознакомления игрока с базовыми механиками, на этом уровне игрок должен научиться планировать создание НИПов (НИПы в стеке не всегда идут в удобном для игрока порядке), и использовать красного НИПа для подбора недосягаемого для персонажа ключа, а затем отбирать его у красного НИПа, также на этом уровне добавляется возможность ознакомления с взаимодействием красного и зеленого НИПа, при котором первый перемещается на один блок вверх появляется опасное препятствие в виде стены, которой нельзя касаться:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 5, уровень должен содержать красных НИПов для подбора недосягаемого для персонажа ключа, а затем отбирать его у красного НИПа, появляется опасное препятствие в виде пола, которого нельзя касаться, открывается возможность не просто прыгать по красным НИПам, но и преодолевать так расстояние:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 6, уровень должен содержать красных, зеленых и желтых НИПов для поэтапного ознакомления игрока с базовыми механиками, на этом уровне игрок должен научиться использовать все виды НИПов и их взаимодействия для подбора недосягаемого для персонажа ключа, а затем отбирать его у красного НИПа, также на этом уровне добавляется возможность ознакомления с взаимодействием красного и желтого НИПа, при котором первый перемещается на один блок вниз:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 7, на этом уровне должно быть уже два ключа, которые необходимо собрать для прохода на следующий уровень, для этого необходимо использовать НИПов для подбора ключа и преодоления высоких препятствий, кроме этого само устройство уровня должно мотивировать игрока продумывать порядок и места расположения НИПов, чтобы НИПы могли попасть в тупик или стать недостижимыми:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 8, на этом уровне должны быть все виды НИПов, которых необходимо использовать для подбора ключа и преодоления высоких препятствий, кроме этого само устройство уровня должно мотивировать игрока продумывать порядок и места расположения НИПов, чтобы НИПы могли попасть в тупик или стать недостижимыми:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 9, на этом уровне должны быть все виды НИПов, которых необходимо использовать для подбора ключа и преодоления высоких препятствий, кроме этого само устройство уровня должно мотивировать игрока продумывать порядок и места расположения НИПов, чтобы НИПы могли попасть в тупик или стать недостижимыми, сам игрок может попасть в тупик или оказаться между НИПами без возможности выбраться:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

Создать уровень 10, заключительный уровень, с поздравлениями игрока и возможностью начать игру с начала:

- [x] разработать схему уровня
- [x] собрать уровень из ассетов
- [x] добавить текстовые подсказки

**Comment by ilynn-zip** [comment]
ed22b8b : добавил макеты для первых трех (4 - включая нулевой) уровней
[документ: макеты уровней](https://github.com/ZhuravlevE/TeamDev/blob/design/maket%20lvl/Макеты%20уровней.pdf)
Остальные уровни лучше макетировать уже в эдиторе, чтобы сразу тестировать на проходимость и механики.

**Comment by ilynn-zip** [comment]
8d47b21 : добавил подсказки для уровней 0-3

**Comment by ilynn-zip** [comment]
Текстовые подсказки на английском. Старался делать их более менее понятными и простыми, но не в лоб.

**Comment by ilynn-zip** [comment]
Добавлены остальные уровни. Протестированы на проходимость. Так же учтена игровая кривая сложности.
