### ISSUE TITLE
Добавить в игру звуки 

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#17]
Добавить озвучку следующих событий:

- [x] появление на уровне
- [x] смерть
- [x] открывание двери
- [x] подбор ключа
- [x] появление врагов

**Comment by ilynn-zip** [comment]
ef8dfca - в игру добавлены звуки, соответствующие различным действиям игрока.
т.к. подбор ключа автоматически соответствовал открыванию двери, чтобы звуки не накладывались в мешанину, было принято решение использовать один звук
