### ISSUE TITLE
Разработать ТЗ 

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#3]
- [x] Тема проекта
- [x] Описание проекта
- [x] Функциональные возможности и игровые механики
- [x] Визуальные макеты
- [x] Технологический стек
- [x] Технологические особенности
- [x] Технические требования

**Comment by ilynn-zip** [comment]
Были дописаны основные пункты.
Подправлены неточности.

**Comment by ZhuravlevE** [comment]
Исправили замечания и утвердили ТЗ
