### ISSUE TITLE
Создать дизайн главного персонажа и вражеских персонажей

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#5]

**Comment by ilynn-zip** [comment]
Дизайн согласован, добавлен в тз.

**Comment by ilynn-zip** [comment]
коммит f993137: добавил основную палитру, использовалась для всех персонажей и окружения в том числе

**Comment by ilynn-zip** [comment]
00c2b7b добавил дизайны персонажей в пнг
