### ISSUE TITLE
Создать тестовый уровень

### ISSUE THREAD

**Issue by ZhuravlevE** [ZhuravlevE/TeamDev#9]
Создать тестовый уровень для теста и отладки механик

**Comment by Raskol-dm** [comment]
Создал нулевой уровень, можете тестировать.

**Comment by ZhuravlevE** [comment]
Тестовый уровень был протестирован автоматически и мануально, были подобраны оптимальные для комфортной игры скорость персонажа и высота прыжка, на основе тестового уровня был настроен cicd для тестирования, билда и деплоя.
